import { CaseStatus, RiskLevel } from '../types/enums';

/**
 * Seed cases for Karnataka agro-zones: Kolar, Chikkaballapur, Bengaluru Rural.
 * Around 13.1°N, 78.1°E.
 * ~25 cases, mix of crops, diseases, statuses, and confidence levels (35% to 96%).
 */
export const SEED_CASES = [
  // --- CLUSTER 1: Kolar Tomato Early Blight (Verified / Analyzed) ---
  {
    id: 'CASE-KA-001',
    crop: 'Tomato',
    growth_stage: 'Fruiting',
    location_name: 'Kolar Agro Sector 4, Srinivaspur Road',
    latitude: 13.1368,
    longitude: 78.1348,
    symptoms: 'Dark concentric brown lesions on mature lower leaves surrounded by yellow chlorotic margins.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Tomato Early Blight',
    confidence: 0.94,
    risk_score: 86.5,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Confirmed Alternaria solani outbreak via stereomicroscope. Immediate copper oxychloride spray scheduled.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    environmental_data: { temperature: 27.5, humidity: 82.0, rainfall: 14.0, nearby_verified_cases: 5 },
  },
  {
    id: 'CASE-KA-002',
    crop: 'Tomato',
    growth_stage: 'Fruiting',
    location_name: 'Mulbagal North Field A, Kolar',
    latitude: 13.1425,
    longitude: 78.1410,
    symptoms: 'Target-like brown spots merging into large blighted patches on foliage.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Tomato Early Blight',
    confidence: 0.91,
    risk_score: 84.0,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Verified in field inspection. Spores actively propagating downwind.',
    created_at: new Date(Date.now() - 4 * 86400000 + 3600000).toISOString(),
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    environmental_data: { temperature: 26.8, humidity: 84.0, rainfall: 16.5, nearby_verified_cases: 4 },
  },
  {
    id: 'CASE-KA-003',
    crop: 'Tomato',
    growth_stage: 'Flowering',
    location_name: 'Bangarapet Road Plot 12, Kolar',
    latitude: 13.1290,
    longitude: 78.1280,
    symptoms: 'Collar rot at stem base accompanied by scattered foliar target spots.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Tomato Early Blight',
    confidence: 0.88,
    risk_score: 81.2,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Cross-validated with soil dampness readings. Severe collar rot detected.',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    environmental_data: { temperature: 28.0, humidity: 80.0, rainfall: 10.0, nearby_verified_cases: 5 },
  },
  {
    id: 'CASE-KA-004',
    crop: 'Tomato',
    growth_stage: 'Fruiting',
    location_name: 'Vemgal Industrial Border Farm, Kolar',
    latitude: 13.1495,
    longitude: 78.1215,
    symptoms: 'Yellow halo surrounding dark necrotized leaf rings.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Tomato Early Blight',
    confidence: 0.85,
    risk_score: 78.0,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.NEEDS_VERIFICATION,
    officer_note: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 27.0, humidity: 79.0, rainfall: 8.0, nearby_verified_cases: 3 },
  },
  {
    id: 'CASE-KA-005',
    crop: 'Tomato',
    growth_stage: 'Vegetative',
    location_name: 'Srinivaspur Block 2, Kolar',
    latitude: 13.1550,
    longitude: 78.1480,
    symptoms: 'Small speckled brown leaf lesions starting on basal canopy.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Tomato Early Blight',
    confidence: 0.72,
    risk_score: 65.0,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.ANALYZED,
    officer_note: null,
    created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 29.1, humidity: 71.0, rainfall: 2.0, nearby_verified_cases: 3 },
  },

  // --- CLUSTER 2: Chikkaballapur Potato Late Blight ---
  {
    id: 'CASE-KA-006',
    crop: 'Potato',
    growth_stage: 'Tuber Growth',
    location_name: 'Chikkaballapur North Basin Plot 9',
    latitude: 13.4325,
    longitude: 77.7275,
    symptoms: 'Water-soaked irregular black lesions on leaf tips with white fungal mildew on underside during morning.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    disease: 'Potato Late Blight',
    confidence: 0.96,
    risk_score: 92.4,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Phytophthora infestans confirmed. Sporangiophores visible. Emergency quarantine containment issued.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    environmental_data: { temperature: 19.5, humidity: 91.0, rainfall: 28.0, nearby_verified_cases: 4 },
  },
  {
    id: 'CASE-KA-007',
    crop: 'Potato',
    growth_stage: 'Tuber Growth',
    location_name: 'Nandi Foothills Agropark, Chikkaballapur',
    latitude: 13.4280,
    longitude: 77.7190,
    symptoms: 'Rapid brown stem purplish lesions and rotten petiole collapse.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    disease: 'Potato Late Blight',
    confidence: 0.92,
    risk_score: 89.0,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Field verified. High canopy moisture accelerating spread.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    environmental_data: { temperature: 20.0, humidity: 89.0, rainfall: 22.0, nearby_verified_cases: 3 },
  },
  {
    id: 'CASE-KA-008',
    crop: 'Potato',
    growth_stage: 'Vegetative',
    location_name: 'Gauribidanur East Zone, Chikkaballapur',
    latitude: 13.4410,
    longitude: 77.7340,
    symptoms: 'Pale green water-soaked spots rapidly enlarging into necrotic black patches.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    disease: 'Potato Late Blight',
    confidence: 0.89,
    risk_score: 87.5,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Verified. Advised systemic cymoxanil + mancozeb application.',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    environmental_data: { temperature: 21.0, humidity: 87.0, rainfall: 19.0, nearby_verified_cases: 4 },
  },
  {
    id: 'CASE-KA-009',
    crop: 'Potato',
    growth_stage: 'Tuber Growth',
    location_name: 'Peresandra Valley Field 3, Chikkaballapur',
    latitude: 13.4502,
    longitude: 77.7412,
    symptoms: 'Blighting of apical shoots and foul-smelling decomposing foliage.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    disease: 'Potato Late Blight',
    confidence: 0.79,
    risk_score: 76.0,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.NEEDS_VERIFICATION,
    officer_note: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 22.0, humidity: 84.0, rainfall: 15.0, nearby_verified_cases: 3 },
  },

  // --- CLUSTER 3: Bengaluru Rural (Hoskote / Devanahalli) Corn Southern Rust ---
  {
    id: 'CASE-KA-010',
    crop: 'Corn',
    growth_stage: 'Silking',
    location_name: 'Hoskote East Sector Block 7, Bengaluru Rural',
    latitude: 13.0722,
    longitude: 77.7981,
    symptoms: 'Dense cinnamon-brown circular to oval pustules scattered densely on upper leaf blade.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: 'Corn Southern Rust',
    confidence: 0.93,
    risk_score: 74.5,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.VERIFIED,
    officer_note: 'Puccinia polysora confirmed. Urediniospores confirmed on leaf scrapings.',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    environmental_data: { temperature: 28.5, humidity: 76.0, rainfall: 5.0, nearby_verified_cases: 3 },
  },
  {
    id: 'CASE-KA-011',
    crop: 'Corn',
    growth_stage: 'Tasseling',
    location_name: 'Sulibele Agro Sector, Bengaluru Rural',
    latitude: 13.0810,
    longitude: 77.8050,
    symptoms: 'Golden powdery eruption on leaf veins with premature dry senescence.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: 'Corn Southern Rust',
    confidence: 0.87,
    risk_score: 71.0,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.VERIFIED,
    officer_note: 'Verified in field. Advisory sent to neighbouring corn growers.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    environmental_data: { temperature: 29.0, humidity: 74.0, rainfall: 3.5, nearby_verified_cases: 2 },
  },
  {
    id: 'CASE-KA-012',
    crop: 'Corn',
    growth_stage: 'Silking',
    location_name: 'Devanahalli South Ridge, Bengaluru Rural',
    latitude: 13.0650,
    longitude: 77.7890,
    symptoms: 'Small raised orange-brown blisters breaking epidermis on mid-canopy leaves.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: 'Corn Southern Rust',
    confidence: 0.84,
    risk_score: 68.0,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.VERIFIED,
    officer_note: 'Confirmed early stage rust pustules.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    environmental_data: { temperature: 30.0, humidity: 71.0, rainfall: 2.0, nearby_verified_cases: 2 },
  },
  {
    id: 'CASE-KA-013',
    crop: 'Corn',
    growth_stage: 'Grain Fill',
    location_name: 'Doddaballapur Border Plot 5, Bengaluru Rural',
    latitude: 13.0780,
    longitude: 77.8120,
    symptoms: 'Heavy rust pustules spreading up to ear husk leaves.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: 'Corn Southern Rust',
    confidence: 0.77,
    risk_score: 64.0,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.NEEDS_VERIFICATION,
    officer_note: null,
    created_at: new Date(Date.now() - 20 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 29.5, humidity: 69.0, rainfall: 4.0, nearby_verified_cases: 3 },
  },

  // --- CLUSTER 4: Chikkaballapur (Sidlaghatta) Tomato Late Blight ---
  {
    id: 'CASE-KA-014',
    crop: 'Tomato',
    growth_stage: 'Fruiting',
    location_name: 'Sidlaghatta Valley Farm 4, Chikkaballapur',
    latitude: 13.3920,
    longitude: 77.8640,
    symptoms: 'Large dark greasy water-soaked lesions across leaves and brown rot on green fruit shoulders.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Late Blight',
    confidence: 0.90,
    risk_score: 83.0,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Verified fruit and leaf late blight. Preventive fungicide recommended for surrounding 5km.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    environmental_data: { temperature: 23.0, humidity: 88.0, rainfall: 18.0, nearby_verified_cases: 2 },
  },
  {
    id: 'CASE-KA-015',
    crop: 'Tomato',
    growth_stage: 'Flowering',
    location_name: 'Chintamani Road Block B, Sidlaghatta',
    latitude: 13.3980,
    longitude: 77.8710,
    symptoms: 'White mildew on leaf undersides following heavy morning fog.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Late Blight',
    confidence: 0.86,
    risk_score: 79.5,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Confirmed. High humidity in valley depression accelerating infection.',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    environmental_data: { temperature: 22.5, humidity: 90.0, rainfall: 21.0, nearby_verified_cases: 2 },
  },
  {
    id: 'CASE-KA-016',
    crop: 'Tomato',
    growth_stage: 'Fruiting',
    location_name: 'Sidlaghatta Sericulture Belt Plot 8',
    latitude: 13.3870,
    longitude: 77.8590,
    symptoms: 'Dark brown sunken lesions with water-soaked edges on tomato calyx.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Late Blight',
    confidence: 0.82,
    risk_score: 76.0,
    risk_level: RiskLevel.HIGH,
    status: CaseStatus.VERIFIED,
    officer_note: 'Field confirmed.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    environmental_data: { temperature: 24.0, humidity: 85.0, rainfall: 14.0, nearby_verified_cases: 2 },
  },

  // --- MIXED STATUSES: Pending AI, Analyzed, More Info, Rejected, Needs Verification ---
  {
    id: 'CASE-KA-017',
    crop: 'Tomato',
    growth_stage: 'Flowering',
    location_name: 'Devanahalli North Greenhouse, Bengaluru Rural',
    latitude: 13.2437,
    longitude: 77.7126,
    symptoms: 'Lower leaf curling with brown necrotic speckling.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Tomato Early Blight',
    confidence: 0.68,
    risk_score: 58.0,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.ANALYZED,
    officer_note: null,
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 27.0, humidity: 72.0, rainfall: 0.0, nearby_verified_cases: 1 },
  },
  {
    id: 'CASE-KA-018',
    crop: 'Potato',
    growth_stage: 'Vegetative',
    location_name: 'Doddaballapur North Agro Basin',
    latitude: 13.2980,
    longitude: 77.5420,
    symptoms: 'Scattered brown blemishes on leaf margins after overnight mist.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    disease: 'Potato Late Blight',
    confidence: 0.61,
    risk_score: 52.0,
    risk_level: RiskLevel.MEDIUM,
    status: CaseStatus.NEEDS_VERIFICATION,
    officer_note: null,
    created_at: new Date(Date.now() - 15 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 23.5, humidity: 79.0, rainfall: 6.0, nearby_verified_cases: 0 },
  },
  {
    id: 'CASE-KA-019',
    crop: 'Corn',
    growth_stage: 'Silking',
    location_name: 'Kolar Gold Fields Agro Sector 2',
    latitude: 12.9610,
    longitude: 78.2710,
    symptoms: 'Isolated small yellow spots on upper foliage.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: 'Corn Southern Rust',
    confidence: 0.48,
    risk_score: 41.0,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.ANALYZED,
    officer_note: null,
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 31.0, humidity: 58.0, rainfall: 0.0, nearby_verified_cases: 0 },
  },
  {
    id: 'CASE-KA-020',
    crop: 'Tomato',
    growth_stage: 'Vegetative',
    location_name: 'Malur Vegetable Market Sector, Kolar',
    latitude: 13.0038,
    longitude: 77.9405,
    symptoms: 'Freshly reported leaf discolouration on young seedling trays.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: null,
    confidence: null,
    risk_score: null,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.PENDING_ANALYSIS,
    officer_note: null,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 28.0, humidity: 65.0, rainfall: 0.0, nearby_verified_cases: 0 },
  },
  {
    id: 'CASE-KA-021',
    crop: 'Potato',
    growth_stage: 'Sprouting',
    location_name: 'Chikkaballapur Agro Hub 3',
    latitude: 13.4350,
    longitude: 77.7210,
    symptoms: 'Recent farmer report of dark shoots emerging from seed tubers.',
    image_url: null,
    disease: null,
    confidence: null,
    risk_score: null,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.PENDING_ANALYSIS,
    officer_note: null,
    created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 22.0, humidity: 75.0, rainfall: 0.0, nearby_verified_cases: 2 },
  },
  {
    id: 'CASE-KA-022',
    crop: 'Corn',
    growth_stage: 'Knee High',
    location_name: 'Bagepalli Outpost Field 1',
    latitude: 13.7820,
    longitude: 77.7940,
    symptoms: 'Slight yellowing on whorl leaves following windy dust storm.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: null,
    confidence: null,
    risk_score: null,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.PENDING_ANALYSIS,
    officer_note: null,
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 32.0, humidity: 50.0, rainfall: 0.0, nearby_verified_cases: 0 },
  },
  {
    id: 'CASE-KA-023',
    crop: 'Tomato',
    growth_stage: 'Fruiting',
    location_name: 'Bangarapet South Plot 22, Kolar',
    latitude: 13.0120,
    longitude: 78.1950,
    symptoms: 'Blurry photo of brown speckles on tomato vine foliage.',
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80',
    disease: 'Suspected Early Blight',
    confidence: 0.38,
    risk_score: 42.0,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.MORE_INFO_REQUIRED,
    officer_note: 'Resolution is too low to distinguish Alternaria lesions from Septoria or physical abrasion. Please re-photograph leaf underside in good daylight.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    verified_at: null,
    environmental_data: { temperature: 27.5, humidity: 68.0, rainfall: 0.0, nearby_verified_cases: 1 },
  },
  {
    id: 'CASE-KA-024',
    crop: 'Potato',
    growth_stage: 'Vegetative',
    location_name: 'Gowribidanur South Ward 2',
    latitude: 13.6080,
    longitude: 77.5120,
    symptoms: 'Uniform yellowing across all lower leaves with no dark concentric rings or mildew.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    disease: 'Nutritional Chlorosis (Non-pathogenic)',
    confidence: 0.35,
    risk_score: 18.0,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.REJECTED,
    officer_note: 'Dismissed as nitrogen deficiency chlorosis. No fungal or bacterial pathogens detected under laboratory assay.',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    environmental_data: { temperature: 29.0, humidity: 52.0, rainfall: 0.0, nearby_verified_cases: 0 },
  },
  {
    id: 'CASE-KA-025',
    crop: 'Corn',
    growth_stage: 'Vegetative',
    location_name: 'Hoskote West Peripheral Plot 3',
    latitude: 13.0610,
    longitude: 77.7710,
    symptoms: 'Mechanical tears and hail puncturing on leaf blades mistaken for pathogen lesions.',
    image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    disease: 'Physical Wind/Hail Damage',
    confidence: 0.42,
    risk_score: 15.0,
    risk_level: RiskLevel.LOW,
    status: CaseStatus.REJECTED,
    officer_note: 'Physical hail impact tear without fungal hyphae or pustule formation. Case closed.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    verified_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    environmental_data: { temperature: 26.0, humidity: 60.0, rainfall: 5.0, nearby_verified_cases: 1 },
  },
];

/**
 * 4 Verified DBSCAN spatial clusters
 */
export const SEED_OUTBREAK_CLUSTERS = [
  {
    cluster_id: 1,
    case_count: 3,
    case_ids: ['CASE-KA-001', 'CASE-KA-002', 'CASE-KA-003'],
    center_latitude: 13.1361,
    center_longitude: 78.1346,
    dominant_disease: 'Tomato Early Blight',
    average_risk_score: 83.9,
    highest_risk_level: RiskLevel.HIGH,
    outbreak_level: RiskLevel.HIGH,
    zone_name: 'Kolar Agro Basin',
    radius_km: 1.8,
  },
  {
    cluster_id: 2,
    case_count: 3,
    case_ids: ['CASE-KA-006', 'CASE-KA-007', 'CASE-KA-008'],
    center_latitude: 13.4338,
    center_longitude: 77.7268,
    dominant_disease: 'Potato Late Blight',
    average_risk_score: 89.6,
    highest_risk_level: RiskLevel.HIGH,
    outbreak_level: RiskLevel.HIGH,
    zone_name: 'Chikkaballapur North',
    radius_km: 2.1,
  },
  {
    cluster_id: 3,
    case_count: 3,
    case_ids: ['CASE-KA-010', 'CASE-KA-011', 'CASE-KA-012'],
    center_latitude: 13.0727,
    center_longitude: 77.7974,
    dominant_disease: 'Corn Southern Rust',
    average_risk_score: 71.2,
    highest_risk_level: RiskLevel.MEDIUM,
    outbreak_level: RiskLevel.MEDIUM,
    zone_name: 'Hoskote - Devanahalli Corn Belt',
    radius_km: 2.4,
  },
  {
    cluster_id: 4,
    case_count: 3,
    case_ids: ['CASE-KA-014', 'CASE-KA-015', 'CASE-KA-016'],
    center_latitude: 13.3923,
    center_longitude: 77.8647,
    dominant_disease: 'Late Blight',
    average_risk_score: 79.5,
    highest_risk_level: RiskLevel.HIGH,
    outbreak_level: RiskLevel.MEDIUM,
    zone_name: 'Sidlaghatta Horticultural Belt',
    radius_km: 1.6,
  },
];

/**
 * 6 Regional Outbreak Incident Advisories / Alerts of mixed severity
 */
export const SEED_ALERTS = [
  {
    warning_id: 'WRN-2026-001',
    cluster_id: 1,
    outbreak_level: RiskLevel.HIGH,
    title: 'High Severity: Tomato Early Blight Outbreak Cluster in Kolar Sector 4',
    message: 'DBSCAN algorithm confirmed 3 verified Alternaria solani cases within 1.8km radius. High pathogen pressure driven by 82% humidity and recent rainfall. Phytosanitary buffer spray recommended for all nightshade plots.',
    center_latitude: 13.1361,
    center_longitude: 78.1346,
    case_count: 3,
    dominant_disease: 'Tomato Early Blight',
    average_risk_score: 83.9,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    warning_id: 'WRN-2026-002',
    cluster_id: 2,
    outbreak_level: RiskLevel.HIGH,
    title: 'Critical Outbreak: Rapid Potato Late Blight Propagation in Chikkaballapur',
    message: 'Verified Phytophthora infestans cluster detected near Nandi Foothills. Microclimate humidity exceeding 90% creates extreme sporulation conditions. Emergency containment protocols activated.',
    center_latitude: 13.4338,
    center_longitude: 77.7268,
    case_count: 3,
    dominant_disease: 'Potato Late Blight',
    average_risk_score: 89.6,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    warning_id: 'WRN-2026-003',
    cluster_id: 3,
    outbreak_level: RiskLevel.MEDIUM,
    title: 'Elevated Risk: Corn Southern Rust Cluster around Hoskote Corridor',
    message: 'Active Puccinia polysora cluster confirmed across 3 maize fields. Spore movement observed along southern wind direction. Field officers should scout vegetative stands within 5km.',
    center_latitude: 13.0727,
    center_longitude: 77.7974,
    case_count: 3,
    dominant_disease: 'Corn Southern Rust',
    average_risk_score: 71.2,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    warning_id: 'WRN-2026-004',
    cluster_id: 4,
    outbreak_level: RiskLevel.MEDIUM,
    title: 'Moderate Alert: Tomato Late Blight Focal Cluster in Sidlaghatta',
    message: 'Localized canopy infection cluster confirmed in Sidlaghatta valley depression. Fruit rot reported in 2 commercial fields. Recommended preventive cymoxanil treatment.',
    center_latitude: 13.3923,
    center_longitude: 77.8647,
    case_count: 3,
    dominant_disease: 'Late Blight',
    average_risk_score: 79.5,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    warning_id: 'WRN-2026-005',
    cluster_id: 101,
    outbreak_level: RiskLevel.LOW,
    title: 'Advisory: Early Season Microclimate Warning for Bengaluru Rural East',
    message: 'Moderate morning fog and relative humidity above 75% recorded in Devanahalli taluk. Routine cultural aeration and prophylactic copper sprays advised for sensitive nursery seedlings.',
    center_latitude: 13.2437,
    center_longitude: 77.7126,
    case_count: 1,
    dominant_disease: 'Tomato Early Blight',
    average_risk_score: 48.0,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    warning_id: 'WRN-2026-006',
    cluster_id: 102,
    outbreak_level: RiskLevel.LOW,
    title: 'Surveillance Notice: Isolated Rust Symptoms in Malur Taluk Perimeter',
    message: 'Minor incidence of maize rust reported; density remains below the critical DBSCAN threshold. Continuous sentinel field monitoring advised over next 72 hours.',
    center_latitude: 13.0038,
    center_longitude: 77.9405,
    case_count: 1,
    dominant_disease: 'Corn Southern Rust',
    average_risk_score: 42.5,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

/**
 * 8 Surveillance Queue fields (Active Surveillance ranking for agricultural officers)
 */
export const SEED_SURVEILLANCE_QUEUE = [
  {
    rank: 1,
    field_id: 'SURV-KA-001',
    name: 'Srinivaspur Perimeter East Block',
    location_name: 'Srinivaspur, Kolar',
    crop: 'Tomato',
    risk_level: RiskLevel.HIGH,
    urgency_score: 96,
    distance_to_cluster: '0.8 km from Cluster #1',
    suspected_pathogen: 'Tomato Early Blight',
    latitude: 13.1410,
    longitude: 78.1380,
    recommended_action: 'Conduct immediate leaf underside inspection and issue foliar copper fungicide advisory.',
    inspection_status: 'PENDING_INSPECTION',
  },
  {
    rank: 2,
    field_id: 'SURV-KA-002',
    name: 'Nandi Valley Horticultural Stand',
    location_name: 'Nandi Hills Base, Chikkaballapur',
    crop: 'Potato',
    risk_level: RiskLevel.HIGH,
    urgency_score: 93,
    distance_to_cluster: '1.1 km from Cluster #2',
    suspected_pathogen: 'Potato Late Blight',
    latitude: 13.4300,
    longitude: 77.7220,
    recommended_action: 'Verify stem collar rot and install spore traps downwind.',
    inspection_status: 'PENDING_INSPECTION',
  },
  {
    rank: 3,
    field_id: 'SURV-KA-003',
    name: 'Vemgal Buffer Plot 3',
    location_name: 'Vemgal Industrial Border, Kolar',
    crop: 'Tomato',
    risk_level: RiskLevel.HIGH,
    urgency_score: 88,
    distance_to_cluster: '1.4 km from Cluster #1',
    suspected_pathogen: 'Tomato Early Blight',
    latitude: 13.1460,
    longitude: 78.1250,
    recommended_action: 'Examine field boundaries for target-spot lesions spreading from CASE-KA-004.',
    inspection_status: 'SCHEDULED',
  },
  {
    rank: 4,
    field_id: 'SURV-KA-004',
    name: 'Peresandra Valley North Sector',
    location_name: 'Peresandra, Chikkaballapur',
    crop: 'Potato',
    risk_level: RiskLevel.HIGH,
    urgency_score: 84,
    distance_to_cluster: '1.9 km from Cluster #2',
    suspected_pathogen: 'Potato Late Blight',
    latitude: 13.4480,
    longitude: 77.7390,
    recommended_action: 'Inspect tuber mounds for foul smell and apical leaf wilt.',
    inspection_status: 'PENDING_INSPECTION',
  },
  {
    rank: 5,
    field_id: 'SURV-KA-005',
    name: 'Sulibele Maize Corridor Stand',
    location_name: 'Sulibele, Bengaluru Rural',
    crop: 'Corn',
    risk_level: RiskLevel.MEDIUM,
    urgency_score: 78,
    distance_to_cluster: '1.3 km from Cluster #3',
    suspected_pathogen: 'Corn Southern Rust',
    latitude: 13.0760,
    longitude: 77.8020,
    recommended_action: 'Sample upper canopy leaves for cinnamon pustule density.',
    inspection_status: 'PENDING_INSPECTION',
  },
  {
    rank: 6,
    field_id: 'SURV-KA-006',
    name: 'Chintamani Road Agro Boundary',
    location_name: 'Sidlaghatta, Chikkaballapur',
    crop: 'Tomato',
    risk_level: RiskLevel.MEDIUM,
    urgency_score: 75,
    distance_to_cluster: '1.6 km from Cluster #4',
    suspected_pathogen: 'Late Blight',
    latitude: 13.3950,
    longitude: 77.8680,
    recommended_action: 'Assess microclimate fog pockets for damp-morning mildew sporulation.',
    inspection_status: 'SCHEDULED',
  },
  {
    rank: 7,
    field_id: 'SURV-KA-007',
    name: 'Devanahalli South Ridge Agro Block',
    location_name: 'Devanahalli, Bengaluru Rural',
    crop: 'Corn',
    risk_level: RiskLevel.MEDIUM,
    urgency_score: 69,
    distance_to_cluster: '2.2 km from Cluster #3',
    suspected_pathogen: 'Corn Southern Rust',
    latitude: 13.0680,
    longitude: 77.7920,
    recommended_action: 'Perform routine leaf scrape survey before silk emergence.',
    inspection_status: 'PENDING_INSPECTION',
  },
  {
    rank: 8,
    field_id: 'SURV-KA-008',
    name: 'Doddaballapur Perimeter Farm 12',
    location_name: 'Doddaballapur, Bengaluru Rural',
    crop: 'Potato',
    risk_level: RiskLevel.LOW,
    urgency_score: 55,
    distance_to_cluster: '4.8 km from Cluster #2',
    suspected_pathogen: 'Potato Late Blight',
    latitude: 13.2910,
    longitude: 77.5480,
    recommended_action: 'Pre-emptive visual audit for moisture stress and foliar blight.',
    inspection_status: 'PENDING_INSPECTION',
  },
];
